# Generated by Django 2.2.4 on 2019-08-12 17:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent_model',
            name='intent_fields',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
            preserve_default=False,
        ),
    ]
