# Generated by Django 2.2.4 on 2019-08-14 09:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0002_intent_model_intent_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intent_model',
            old_name='intent_fields',
            new_name='responses',
        ),
        migrations.AddField(
            model_name='intent_model',
            name='training_phrases',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='say_hi', max_length=66, size=6),
            preserve_default=False,
        ),
    ]
