# Generated by Django 2.2.4 on 2019-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0003_auto_20190814_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('audio', models.FileField(blank=True, default='myaudio.mp3', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='intent_model',
            name='responses',
            field=models.CharField(max_length=250),
        ),
    ]
