# Generated by Django 2.2.4 on 2019-08-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.FileField(blank=True, default='default.mp3', upload_to=''),
        ),
    ]
