# Generated by Django 2.2.4 on 2019-08-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20190807_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumb',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='json',
        ),
    ]
