# Generated by Django 2.2.4 on 2019-08-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20190807_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='json',
            new_name='text',
        ),
    ]
