# Generated by Django 2.2.4 on 2019-08-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20190812_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='MyModel',
        ),
    ]
